const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const {chromium}=require('../unit01/node_modules/playwright');
const {execFileSync}=require('child_process');
const repo=path.resolve(__dirname,'../..'),course='the-educator/learning/courses/new-cpcs351',dir=path.join(repo,course);
const base=process.env.BASE_URL||'http://127.0.0.1:8765',out=process.env.OUTPUT_DIR||path.join(__dirname,'results');fs.mkdirSync(out,{recursive:true});
const checks=[],errors=[];async function check(name,fn){try{await fn();checks.push({name,passed:true})}catch(e){checks.push({name,passed:false,error:e.message})}}
function htmls(d){return fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?htmls(path.join(d,e.name)):e.name.endsWith('.html')?[path.join(d,e.name)]:[])}
const files=htmls(dir),urls=files.map(f=>path.relative(dir,f).replaceAll('\\','/'));
function txt(s){return s.replace(/<[^>]*>/g,' ').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&#39;/g,"'").replace(/&quot;/g,'"').replace(/\s+/g,' ').trim()}
(async()=>{
 await check('all local links, stylesheet paths and fragments resolve',()=>{const missing=[];for(const file of files){const html=fs.readFileSync(file,'utf8');for(const match of html.matchAll(/(?:href|src)="([^"]+)"/g)){const value=match[1];if(/^(https?:|mailto:|data:)/.test(value))continue;const u=new URL(value,'http://local/'+path.relative(repo,file));let target=path.join(repo,decodeURIComponent(u.pathname));if(fs.existsSync(target)&&fs.statSync(target).isDirectory())target=path.join(target,'index.html');if(!fs.existsSync(target)){missing.push({file:path.relative(dir,file),value});continue;}if(u.hash&&target.endsWith('.html')){const id=decodeURIComponent(u.hash.slice(1));const content=fs.readFileSync(target,'utf8');if(!content.includes(`id="${id}"`)&&!content.includes(`id='${id}'`))missing.push({file:path.relative(dir,file),value,reason:'missing fragment'});}}}assert.deepEqual(missing,[])});
 await check('moved exercise content is preserved at destination',()=>{const moves=JSON.parse(fs.readFileSync(path.join(__dirname,'migration.json'))).moves;const absent=moves.filter(m=>!txt(fs.readFileSync(path.join(dir,m.to),'utf8')).includes(m.text));assert.deepEqual(absent.map(m=>({from:m.from,to:m.to,anchor:m.anchor})),[])});
 await check('all original substantial unit paragraphs remain somewhere in the restructured course',()=>{const current=files.map(f=>txt(fs.readFileSync(f,'utf8'))).join(' '),unitFiles=files.filter(f=>f.includes('/units/')&&!f.includes('/practice/'));const missing=[];let count=0;for(const f of unitFiles){const original=execFileSync('git',['show','6f2320d:'+path.relative(repo,f)],{cwd:repo,encoding:'utf8'});for(const m of original.matchAll(/<p(?: [^>]*)?>(.*?)<\/p>/gs)){const value=txt(m[1]);if(value.length<30)continue;count++;if(!current.includes(value))missing.push({file:path.relative(dir,f),text:value})}}assert.deepEqual(missing,[]);fs.writeFileSync(path.join(out,'paragraph-preservation.json'),JSON.stringify({source:'6f2320de902f9cd798af4235bbbe4f15eec7c4e9',paragraphsChecked:count,missing},null,2))});
 const browser=await chromium.launch({executablePath:process.env.CHROME_PATH,...(process.env.BROWSER_PROXY?{proxy:{server:process.env.BROWSER_PROXY}}:{})});
 const browserVersion=browser.version();
 const page=await browser.newPage({viewport:{width:1440,height:900},ignoreHTTPSErrors:process.env.PROXY_TLS_INTERCEPTION==='1'});page.on('pageerror',e=>errors.push(e.message));
 if(process.env.BLOCK_EXTERNAL_FONTS==='1'){await page.route('https://fonts.googleapis.com/**',r=>r.abort());await page.route('https://fonts.gstatic.com/**',r=>r.abort())}
 const axeSummaries=[];
 let visited=0;
 for(const file of urls){
  await page.setViewportSize({width:1440,height:900});
  const response=await page.goto(`${base}/${course}/${file}`,{waitUntil:'networkidle'});await check(file+' HTTP and navigation',async()=>{assert.equal(response.status(),200);assert.equal(await page.locator('h1').count(),1);assert.equal(await page.locator('.course-places a').count(),5);assert.equal(await page.locator('.course-menu').count(),1);const footer=await page.locator('.site-footer').boundingBox(),main=await page.locator('main').boundingBox();assert.ok(footer.y>=main.y+main.height-2)});
  await check(file+' bytes match current source',async()=>assert.equal(await response.text(),fs.readFileSync(path.join(dir,file),'utf8')));
  await check(file+' heading order',async()=>{const hs=await page.locator('main h1,main h2,main h3,main h4').evaluateAll(es=>es.map(e=>+e.tagName[1]));for(let i=1;i<hs.length;i++)assert.ok(hs[i]<=hs[i-1]+1,JSON.stringify(hs))});
  await page.addScriptTag({path:require.resolve('../unit01/node_modules/axe-core/axe.min.js')});const axe=await page.evaluate(()=>axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}}));axeSummaries.push({file,violations:axe.violations.map(v=>({id:v.id,targets:v.nodes.map(n=>n.target)})),incomplete:axe.incomplete.map(v=>v.id)});await check(file+' axe desktop',()=>assert.deepEqual(axeSummaries.at(-1).violations,[]));
  for(const width of [320,390,768,980,981,1440]){await page.setViewportSize({width,height:900});await check(file+' reflow '+width,async()=>assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)));}
  await page.setViewportSize({width:390,height:844});await page.locator('.course-menu').evaluate(e=>e.open=true);await check(file+' expanded mobile navigation reflow',async()=>assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)));const mobileAxe=await page.evaluate(()=>axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}}));const mobileSummary={file,mobile:true,violations:mobileAxe.violations.map(v=>({id:v.id,targets:v.nodes.map(n=>n.target)})),incomplete:mobileAxe.incomplete.map(v=>v.id)};axeSummaries.push(mobileSummary);await check(file+' axe mobile with menu expanded',()=>assert.deepEqual(mobileSummary.violations,[]));await page.locator('.course-menu').evaluate(e=>e.open=false);
  if(['index.html','learn/index.html','practice/index.html','studios/index.html','challenges/index.html','quick-checks/index.html','studios/studio01.html','practice/unit01.html','units/01/quality.html','units/02/index.html'].includes(file)){for(const width of [390,1440]){await page.setViewportSize({width,height:900});await page.screenshot({path:path.join(out,file.replaceAll('/','-')+'-'+width+'.png'),fullPage:true})}}
  visited++;if(visited%10===0)console.log(`Verified ${visited}/${urls.length} pages`);
 }
 await page.setViewportSize({width:390,height:844});await page.goto(`${base}/${course}/practice/?unit=01`);
 await check('catalog filter preselect, keyboard change and all-items reset',async()=>{assert.equal(await page.locator('[data-unit-filter]').inputValue(),'01');assert.equal(await page.locator('.catalog-card:visible').count(),3);await page.locator('[data-unit-filter]').selectOption('07');assert.equal(await page.locator('.catalog-card:visible').count(),1);await page.locator('[data-unit-filter]').selectOption('all');assert.equal(await page.locator('.catalog-card:visible').count(),12)});
 await check('mobile course menu exposes all five spaces',async()=>{assert.equal(await page.locator('.course-menu').evaluate(e=>e.open),false);await page.locator('.course-menu summary').focus();await page.keyboard.press('Enter');assert.equal(await page.locator('.course-places a:visible').count(),5);await page.locator('.course-places .place-studios').click();await page.waitForURL('**/studios/');assert.equal(await page.locator('.course-places [aria-current="location"]').count(),1)});
 for(const topic of ['professional','engineering','quality','process','systems','responsibility','context']){await page.goto(`${base}/${course}/practice/u01-${topic}.html`);await check(topic+' independent attempt has a label and working feedback',async()=>{assert.equal(await page.locator('.micro-attempt').count(),1);assert.equal(await page.locator('textarea').count(),1);const area=page.locator('textarea');const id=await area.getAttribute('id');assert.equal(await page.locator(`label[for="${id}"]`).count(),1);await area.fill('A justified decision supported by observable evidence.');await page.locator('.micro-feedback summary').click();assert.ok(await page.locator('.micro-feedback').evaluate(e=>e.open))})}
 await page.goto(`${base}/${course}/units/01/practice.html`);
 await check('canonical ungraded quiz still answers, locks and resets all five questions',async()=>{assert.equal(await page.locator('.quiz-q').count(),5);for(const q of await page.locator('.quiz-q').all()){const answer=await q.getAttribute('data-answer');await q.locator(`[data-choice="${answer}"]`).click();assert.equal(await q.getAttribute('data-correct'),'true');await q.locator('.u01-reset').click();assert.equal(await q.getAttribute('data-attempted'),'false')}});
 await page.goto(`${base}/${course}/units/01/workshop.html`);
 await check('canonical workshop export retains entered reasoning',async()=>{await page.locator('#risk-1-symptom').fill('Preserved workshop evidence');const pending=page.waitForEvent('download');await page.locator('#u01-download-notes').click();const download=await pending;await download.saveAs(path.join(out,'workshop.txt'));assert.ok(fs.readFileSync(path.join(out,'workshop.txt'),'utf8').includes('Preserved workshop evidence'))});
 await page.goto(`${base}/${course}/units/01/transfer.html`);
 await check('canonical individual transfer export works',async()=>{await page.locator('#u01-exit-response').fill('Independent transfer evidence');const pending=page.waitForEvent('download');await page.locator('#u01-download-exit').click();const download=await pending;await download.saveAs(path.join(out,'transfer.txt'));assert.ok(fs.readFileSync(path.join(out,'transfer.txt'),'utf8').includes('Independent transfer evidence'))});
 await page.goto(`${base}/${course}/units/01/#quality`);await check('old Unit 01 fragment route remains compatible',async()=>{await page.waitForURL('**/quality.html#quality');assert.equal(await page.locator('.micro-attempt').count(),0);assert.equal(await page.locator('.answer-contrast article').count(),2);assert.equal(await page.locator('.related-links a[href*="practice/u01-quality.html"]').count(),1)});
 await page.goto(`${base}/${course}/learn/`);await check('skip link targets main',async()=>{await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement.className),'skip');await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>document.activeElement.id),'main')});
 const nojs=await browser.newPage({javaScriptEnabled:false,ignoreHTTPSErrors:process.env.PROXY_TLS_INTERCEPTION==='1'});if(process.env.BLOCK_EXTERNAL_FONTS==='1'){await nojs.route('https://fonts.googleapis.com/**',r=>r.abort());await nojs.route('https://fonts.gstatic.com/**',r=>r.abort())}await nojs.goto(`${base}/${course}/practice/`,{waitUntil:'networkidle'});await check('no-JS catalog and fixed navigation stay readable',async()=>{assert.equal(await nojs.locator('.catalog-card:visible').count(),12);assert.equal(await nojs.locator('.fallback-nav a').count(),5)});await nojs.close();
 await check('no uncaught JavaScript errors',()=>assert.deepEqual(errors,[]));await browser.close();
 const result={completed:true,url:base,browser:browserVersion,revision:'20261010-places1',date:new Date().toISOString(),tlsValidation:process.env.PROXY_TLS_INTERCEPTION!=='1',externalFontsBlocked:process.env.BLOCK_EXTERNAL_FONTS==='1',checks,errors};fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(result,null,2));fs.writeFileSync(path.join(out,'axe-summary.json'),JSON.stringify(axeSummaries,null,2));console.log(JSON.stringify({pages:urls.length,passed:checks.filter(c=>c.passed).length,failed:checks.filter(c=>!c.passed)},null,2));process.exitCode=checks.some(c=>!c.passed)?1:0;
})().catch(e=>{console.error(e);fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({completed:false,checks,errors,fatal:e.message},null,2));process.exit(1)});
