(()=>{
  const topicName='Design Patterns & GRASP Responsibility Assignment';
  const fig=(src,alt,caption)=>{const f=document.createElement('figure');f.className='t11-infographic';f.innerHTML=`<img src="assets/${src}" alt="${alt}" loading="lazy"><figcaption>${caption}</figcaption>`;return f};
  const byHeading=(text)=>[...document.querySelectorAll('.section')].find(s=>(s.querySelector('h2')?.textContent||'').includes(text));
  const removeSeq=(n=Infinity)=>[...document.querySelectorAll('.seq-wrap')].slice(0,n).forEach(x=>x.remove());
  const setTopicLabels=()=>{
    document.querySelectorAll('.topic-side-head strong').forEach(x=>x.textContent=topicName);
    document.querySelectorAll('.crumbs').forEach(x=>x.innerHTML=x.innerHTML.replace('Topic 11 · Responsibility Assignment Patterns',`Topic 11 · ${topicName}`));
    const first=document.querySelector('.topic-side-list a'); if(first) first.lastChild.nodeValue=' Foundations & Pattern Map';
  };
  const foundations=()=>{
    if(document.body.dataset.page!=='1'||document.querySelector('#design-pattern-foundations'))return;
    document.querySelector('.p11-hero')?.remove();
    [...document.querySelectorAll('.section')].filter(s=>(s.querySelector('h2')?.textContent||'').includes('Pattern map')).forEach(s=>s.remove());
    [...document.querySelectorAll('.rule')].filter(r=>r.textContent.includes('Study strategy')).forEach(r=>r.remove());
    const wrap=document.createElement('div');wrap.id='design-pattern-foundations';wrap.innerHTML=`
      <section class="section"><div class="pattern-banner foundation-banner"><span class="pattern-icon">🧭</span><div><span class="pill">FOUNDATION</span><h2>What is a Design Pattern?</h2><p>A reusable design idea for a recurring software-design problem. It is a blueprint to adapt to a context—not finished code to copy.</p></div></div><div class="t11-mini-flow"><div><b>1 · Recognize</b>Identify the recurring problem and its design forces.</div><div><b>2 · Match & Adapt</b>Choose a fitting pattern and map its roles to your classes.</div><div><b>3 · Evaluate</b>Check coupling, cohesion, complexity, flexibility, and change impact.</div></div><div class="rule"><b>Pattern ≠ code snippet ≠ algorithm.</b> A pattern organizes responsibilities and collaborators; implementation still depends on the system.</div></section>
      <section class="section"><h2>Where design fits in the software life cycle</h2><figure class="t11-infographic"><img src="assets/lsandout.png" alt="Requirements lead to design solution models, then construction and code" loading="eager"><figcaption>Requirements define the problem; design produces solution models; construction turns those models into code. Patterns support the design stage by capturing reusable solution knowledge.</figcaption></figure></section>
      <section class="section"><h2>Why Design Patterns matter</h2><div class="hook-grid"><div class="hook crea-hook"><span class="big-icon">🧰</span><b>Reuse experience</b><p>Start from proven design knowledge instead of rediscovering recurring solutions.</p></div><div class="hook stru-hook"><span class="big-icon">💬</span><b>Shared vocabulary</b><p>Pattern names communicate a larger design idea quickly across a team.</p></div><div class="hook beha-hook"><span class="big-icon">🧠</span><b>Improve reasoning</b><p>Patterns make responsibility, collaboration, and trade-offs explicit.</p></div></div></section>
      <section class="section"><h2>From architecture to object design</h2><table class="compact-table"><tr><th>Dimension</th><th>Architectural Pattern</th><th>Design Pattern</th></tr><tr><td>Scale</td><td>Whole system or major subsystems</td><td>Classes, objects, and collaborations</td></tr><tr><td>Main question</td><td>How should the major parts of the system be organized?</td><td>How should a recurring object/class design problem be solved?</td></tr><tr><td>Impact</td><td>Broad and system-wide</td><td>More localized inside the architecture</td></tr><tr><td>Examples</td><td>Layered Architecture · Client–Server · MVC</td><td>Singleton · Builder · Adapter · Observer</td></tr><tr><td>Relationship</td><td colspan="2"><strong>They coexist:</strong> one architecture can contain many design patterns.</td></tr></table><div class="flow"><span>Architecture</span><i>→ contains →</i><span>Components / Subsystems</span><i>→ use →</i><span>Design Patterns</span></div></section>
      <section class="section"><h2>Where the pattern idea came from</h2><div class="flow"><span>Christopher Alexander</span><i>→</i><span>GoF · 1994</span><i>→</i><span>23 classic OO patterns</span><i>→</i><span>Shared software vocabulary</span></div><p>The pattern idea originated in architecture and was adapted to software. The Gang of Four catalog made named object-oriented design solutions widely teachable and discussable.</p></section>
      <section class="section"><h2>The GoF catalog at a glance</h2><figure class="t11-infographic"><img src="assets/designpatternsandcat.png" alt="Catalog of Creational, Structural, and Behavioral design patterns" loading="lazy"><figcaption>GoF patterns are classified by intent: Creational patterns organize object creation, Structural patterns organize composition, and Behavioral patterns organize interaction.</figcaption></figure><div class="rule"><b>Study strategy:</b> start with the design problem, then choose a family and pattern. Do not force a favorite pattern into a problem that does not need it.</div></section>`;
    document.querySelector('.hero')?.insertAdjacentElement('afterend',wrap);
  };
  const controller=()=>{
    if(document.body.dataset.page!=='8')return;
    const hero=document.querySelector('.p11-hero'); if(hero) hero.replaceWith(fig('chechoutsquanceuml.png','Initial checkout design showing presentation coupling and too many GUI responsibilities.','Problem first: the GUI talks directly to business objects, creating tight coupling and too many presentation responsibilities.'));
    removeSeq();
    const s=byHeading('Controller pattern'); if(s&&!document.querySelector('[data-controller-solution]')){const f=fig('controllerdespat.png','CheckoutController receives the actor request between the GUI and business logic.','Controller receives the system event and coordinates the use case; it should delegate domain work rather than absorb it.');f.dataset.controllerSolution='1';s.insertAdjacentElement('afterend',f)}
  };
  const controllerQuality=()=>{
    if(document.body.dataset.page!=='9')return;
    removeSeq();
    document.querySelector('.question-strip')?.remove();
    [...document.querySelectorAll('.section')].filter(s=>/Bloated Controller|Symptoms|Conventional Design|Healthy vs Bloated/i.test(s.textContent||'')).forEach(s=>s.remove());
    const anchor=document.querySelector('.hero'); if(!anchor||document.querySelector('[data-bloated-visual]'))return;
    const intro=document.createElement('section');intro.className='section';intro.innerHTML='<h2>Controller Quality — coordinate, do not centralize</h2><p>A Controller should receive system events and coordinate the use case. Quality drops when unrelated responsibilities accumulate in one controller instead of being delegated to the objects that own the knowledge or behavior.</p>';
    anchor.insertAdjacentElement('afterend',intro);
    const bad=fig('bottledcontroller.png','Bloated Controller infographic showing one StoreController handling product search, order creation, customer updates, payment processing, and order status changes.','Bloated Controller design smell: one controller handles many unrelated actor requests and absorbs domain responsibilities. The result is low cohesion, high coupling, and a design that is harder to change and maintain.');bad.dataset.bloatedVisual='1';intro.insertAdjacentElement('afterend',bad);
    const takeaway=document.createElement('div');takeaway.className='rule';takeaway.innerHTML='<b>Better design:</b> keep the controller focused on coordination and delegate domain responsibilities to the appropriate business objects. This supports separation of concerns, higher cohesion, and lower coupling.';bad.insertAdjacentElement('afterend',takeaway);
    takeaway.insertAdjacentElement('afterend',fig('checkousquancelumlanswer.png','Completed checkout sequence with a focused CheckoutController coordinating business collaborators.','Compare the improvement: CheckoutController remains the system-event coordinator while collaborators perform the work associated with their own responsibilities.'));
  };
  const expert=()=>{
    if(document.body.dataset.page!=='10')return;
    document.querySelector('.hero h1')&&(document.querySelector('.hero h1').textContent='GRASP Information Expert — Put Work Where the Knowledge Is');
    document.querySelector('.hero .eyebrow')&&(document.querySelector('.hero .eyebrow').textContent='10 · GRASP · INFORMATION EXPERT');
    document.querySelector('.seq-wrap')?.remove();
    byHeading('Checkout: move availability behavior to Document')?.remove();
    const hero=document.querySelector('.p11-hero'); if(hero&&!document.querySelector('[data-expert-visual]')){const f=fig('experpattern.png','Infographic comparing a weak checkout design with an improved Information Expert design.','Information Expert: assign a responsibility to the object that already has the information needed to fulfill it. Document owns availability, so it answers and changes that state.');f.dataset.expertVisual='1';hero.insertAdjacentElement('afterend',f)}
  };
  const creator=()=>{
    if(document.body.dataset.page!=='11')return;
    [...document.querySelectorAll('.section')].filter(s=>/Creator rule|chapter's Creator activity/i.test(s.querySelector('h2')?.textContent||'')).forEach(s=>s.remove()); removeSeq(1);
    const hero=document.querySelector('.hero'); if(hero&&!document.querySelector('[data-creator-visual]')){const f=fig('creatorpattern.png','Infographic explaining GRASP Creator and its creation-responsibility criteria.','Creator: assign object creation to the class with the strongest containing, recording, using, aggregation, or initialization-data relationship.');f.dataset.creatorVisual='1';hero.insertAdjacentElement('afterend',f);const bridge=document.createElement('div');bridge.className='t11-bridge';bridge.innerHTML='<strong>Course connection:</strong> CheckoutController may create Loan in this example because it has the required user/document information at that point. The rule is not “controllers create objects”; the rule is to choose the class with the strongest creation relationship or data.';f.insertAdjacentElement('afterend',bridge)}
  };
  const integrated=()=>{
    if(document.body.dataset.page!=='12')return;
    const hero=document.querySelector('.p11-hero'); if(hero){hero.querySelector('h2')&&(hero.querySelector('h2').textContent='One use case, three responsibility decisions');hero.querySelector('.lead')&&(hero.querySelector('.lead').textContent='Read the collaboration as a chain: Controller receives the system event → Information Expert owns knowledge-based work → Creator assigns object creation.')}
    const first=document.querySelector('.seq-wrap'); if(first&&!document.querySelector('.integration-strip')){const d=document.createElement('div');d.className='integration-strip';d.innerHTML='<div><b>Controller</b><span>Who receives?</span></div><i>→</i><div><b>Information Expert</b><span>Who knows?</span></div><i>→</i><div><b>Creator</b><span>Who creates?</span></div>';first.insertAdjacentElement('beforebegin',d)}
  };
  const review=()=>{
    if(document.body.dataset.page!=='13')return;
    const article=document.querySelector('article.content');if(!article)return;
    [...article.querySelectorAll('.section,.rule')].forEach(x=>x.remove());
    const nav=article.querySelector('.lesson-nav');
    const wrap=document.createElement('div');wrap.innerHTML=`<section class="section"><h2>GoF Design Patterns</h2><table class="compact-table"><tr><th>Pattern</th><th>Family</th><th>Recognition question</th></tr><tr><td>Singleton</td><td>Creational</td><td>Must there be exactly one controlled shared instance?</td></tr><tr><td>Builder</td><td>Creational</td><td>Is construction complex, stepwise, or highly configurable?</td></tr><tr><td>Factory Method</td><td>Creational</td><td>Should subclasses decide which concrete product is created?</td></tr><tr><td>Facade</td><td>Structural</td><td>Do clients need one simpler entry point to a complex subsystem?</td></tr><tr><td>Adapter</td><td>Structural</td><td>Do useful components have incompatible interfaces?</td></tr><tr><td>Observer</td><td>Behavioral</td><td>Should subscribers react automatically when a publisher changes?</td></tr></table></section><section class="section"><h2>GRASP Responsibility Patterns</h2><table class="compact-table"><tr><th>Pattern</th><th>Responsibility question</th><th>Core move</th></tr><tr><td>Controller</td><td>Who should receive a system event from presentation?</td><td>Receive and coordinate; delegate domain work.</td></tr><tr><td>Information Expert</td><td>Who already has the information needed?</td><td>Put behavior with the knowledge.</td></tr><tr><td>Creator</td><td>Who should create this object?</td><td>Choose the strongest relationship or creation-data owner.</td></tr></table></section><section class="section"><h2>Final mental model</h2><div class="pattern-grid"><div class="pattern-card creational"><b>Creational</b><p>Control object construction.</p></div><div class="pattern-card structural"><b>Structural</b><p>Organize connections and composition.</p></div><div class="pattern-card behavioral"><b>Behavioral</b><p>Organize interaction and change.</p></div><div class="pattern-card grasp"><b>GRASP</b><p>Assign responsibilities to the right objects.</p></div></div></section><section class="section"><h2>Quick design challenge</h2><div class="decision"><b>Payment SDK mismatch</b><span><strong>Adapter</strong> — translate the interface.</span><b>Complex report construction</b><span><strong>Builder</strong> — construct through explicit steps.</span><b>Order-state notifications</b><span><strong>Observer</strong> — notify subscribers.</span><b>Checkout request from UI</b><span><strong>Controller</strong> — receive and coordinate the system event.</span><b>Document availability</b><span><strong>Information Expert</strong> — Document owns the state.</span><b>Create a contained line item</b><span><strong>Creator</strong> — assign creation to the containing/closely related object.</span></div></section>`;
    nav?.insertAdjacentElement('beforebegin',wrap);
  };
  const mount=()=>{if(document.body.dataset.topic!=='11')return;setTopicLabels();foundations();controller();controllerQuality();expert();creator();integrated();review()};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
})();