(()=>{
  const mount=()=>{
    if(document.body.dataset.topic!=='11'||document.body.dataset.page!=='1')return;
    const content=document.querySelector('article.content');if(!content||document.querySelector('#design-pattern-foundations'))return;
    document.querySelector('.p11-hero')?.remove();
    [...document.querySelectorAll('.section')].filter(s=>(s.querySelector('h2')?.textContent||'').includes('Pattern map')).forEach(s=>s.remove());
    [...document.querySelectorAll('.rule')].filter(r=>r.textContent.includes('Study strategy')).forEach(r=>r.remove());
    const wrap=document.createElement('div');wrap.id='design-pattern-foundations';wrap.innerHTML=`
      <section class="section">
        <div class="pattern-banner" style="background:linear-gradient(135deg,#eef2ff,#f0fdfa);border-color:#c7d2fe"><span class="pattern-icon">🧭</span><div><span class="pill">FOUNDATION</span><h2>What is a Design Pattern?</h2><p>A design pattern is a reusable design idea for a recurring software-design problem. It is a blueprint to adapt to a context—not finished code to copy.</p></div></div>
        <div class="t11-mini-flow"><div><b>1 · Recognize</b>Identify the recurring problem and its design forces.</div><div><b>2 · Adapt</b>Map the pattern roles to your own classes and objects.</div><div><b>3 · Evaluate</b>Check coupling, cohesion, complexity, flexibility, and change impact.</div></div>
        <div class="rule"><b>Pattern ≠ code snippet ≠ algorithm.</b> A pattern describes how responsibilities and collaborators can be organized; the implementation still depends on your system.</div>
      </section>
      <section class="section"><h2>Where does design fit in the software life cycle?</h2><figure class="t11-infographic"><img src="assets/lsandout.png" alt="Infographic showing requirements leading to design solution models and then construction and code" loading="eager"><figcaption>Requirements define the problem; design produces solution models; construction turns those models into working code. Design patterns support the design stage by capturing reusable solution knowledge.</figcaption></figure></section>
      <section class="section"><h2>Why Design Patterns matter</h2><div class="hook-grid"><div class="hook crea-hook"><span class="big-icon">🧰</span><b>Reuse experience</b><p>Start from a proven design idea instead of rediscovering the same solution from zero.</p></div><div class="hook stru-hook"><span class="big-icon">💬</span><b>Shared vocabulary</b><p>Names such as Adapter or Observer communicate a larger design idea quickly.</p></div><div class="hook beha-hook"><span class="big-icon">🧠</span><b>Improve reasoning</b><p>Patterns make responsibility, collaboration, and trade-offs explicit.</p></div></div></section>
      <section class="section"><h2>Where did the idea come from?</h2><div class="flow"><span>Christopher Alexander</span><i>→</i><span>GoF · 1994</span><i>→</i><span>23 classic OO patterns</span><i>→</i><span>Shared software vocabulary</span></div><p>The pattern idea originated in architecture and was adapted to software. The Gang of Four catalog made named object-oriented design solutions widely teachable and discussable across projects and languages.</p></section>
      <section class="section"><h2>Design Pattern vs Architectural Pattern</h2><table class="compact-table"><tr><th>Dimension</th><th>Architectural Pattern</th><th>Design Pattern</th></tr><tr><td>Scale</td><td>Whole system or major subsystems</td><td>Classes, objects, and collaborations</td></tr><tr><td>Main question</td><td>How should the major parts of the system be organized?</td><td>How should a recurring object/class design problem be solved?</td></tr><tr><td>Impact</td><td>Broad and system-wide</td><td>More localized inside the architecture</td></tr><tr><td>Examples</td><td>Layered Architecture · Client–Server · MVC</td><td>Singleton · Builder · Adapter · Observer</td></tr><tr><td>Relationship</td><td colspan="2"><strong>They coexist:</strong> one architecture can contain many design patterns.</td></tr></table><div class="flow"><span>Architectural Pattern</span><i>→ contains →</i><span>Components / Subsystems</span><i>→ use →</i><span>Design Patterns</span></div></section>
      <section class="section"><h2>The GoF catalog at a glance</h2><figure class="t11-infographic"><img src="assets/designpatternsandcat.png" alt="Infographic catalog of Creational, Structural, and Behavioral design patterns" loading="lazy"><figcaption>The catalog is classified by intent: Creational patterns organize object creation, Structural patterns organize composition, and Behavioral patterns organize interaction and responsibility.</figcaption></figure><div class="rule"><b>Study strategy:</b> start with the design question, then choose a suitable family and pattern. Do not force a favorite pattern into a problem that does not need it.</div></section>`;
    const hero=document.querySelector('.hero');hero?.insertAdjacentElement('afterend',wrap);
  };
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
})();