const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const {chromium}=require('playwright');
const base=process.env.BASE_URL||'http://127.0.0.1:8765';const root='/the-educator/learning/courses/new-cpcs351/units/01/';
const routes=JSON.parse(fs.readFileSync(path.join(__dirname,'../../the-educator/learning/courses/new-cpcs351/units/01/unit01-routes.json')));
const out=process.env.OUTPUT_DIR||'multipage-results';fs.mkdirSync(out,{recursive:true});const resultFile=path.join(out,'results.json');if(fs.existsSync(resultFile))fs.unlinkSync(resultFile);const checks=[],errors=[];
async function check(name,fn){try{await fn();checks.push({name,passed:true})}catch(e){checks.push({name,passed:false,error:e.message})}}
let activeBrowser;
(async()=>{const browser=await chromium.launch({...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{}),...(process.env.BROWSER_PROXY?{proxy:{server:process.env.BROWSER_PROXY}}:{})});
activeBrowser=browser;const page=await browser.newPage({ignoreHTTPSErrors:process.env.PROXY_TLS_INTERCEPTION==='1',viewport:{width:1440,height:900}});page.on('pageerror',e=>errors.push(e.message));if(process.env.BLOCK_EXTERNAL_FONTS==='1'){await page.route('https://fonts.googleapis.com/**',r=>r.abort());await page.route('https://fonts.gstatic.com/**',r=>r.abort());}
for(const file of routes.pages){
 await page.goto(base+root+file,{waitUntil:'networkidle'});
 assert.equal(await page.locator('body').getAttribute('data-unit-revision'),'20261009-focus2','Deployment still pending');
 await check(file+' headings and active topic',async()=>{assert.equal(await page.locator('h1').count(),1);assert.equal(await page.locator('.unit-sidebar [aria-current="page"]').count(),1);const layout=await page.evaluate(()=>({footer:document.querySelector('.site-footer').getBoundingClientRect().top,shellBottom:document.querySelector('.unit-shell').getBoundingClientRect().bottom,fonts:[...document.querySelectorAll('.studio-phases p,.story-question p')].map(e=>getComputedStyle(e).fontSize)}));assert.ok(layout.footer>=layout.shellBottom-1,'Course footer must follow the unit');assert.ok(layout.fonts.every(f=>f==='18px'),'Decision prompts and workshop phases use 18px text');const h=await page.locator('h1,h2,h3,h4').evaluateAll(es=>es.map(e=>+e.tagName[1]));for(let i=1;i<h.length;i++)assert.ok(h[i]<=h[i-1]+1,JSON.stringify(h));});
 await check(file+' all internal fragments resolve',async()=>{const links=await page.locator('a[href]').evaluateAll(es=>es.map(e=>e.getAttribute('href')).filter(h=>!/^https?:|mailto:/.test(h)));for(const l of links){const u=new URL(l,page.url());if(u.pathname!==new URL(page.url()).pathname||!u.hash)continue;assert.equal(await page.locator(u.hash).count(),1,l)}});
 await page.addScriptTag({path:require.resolve('axe-core/axe.min.js')});const axe=await page.evaluate(async()=>axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}}));fs.writeFileSync(path.join(out,file+'-axe.json'),JSON.stringify(axe));await check(file+' axe',()=>assert.equal(axe.violations.length,0,JSON.stringify(axe.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)})))));
 if(await page.locator('.story-visual img').count()) await check(file+' original illustration loads with description',async()=>{for(const img of await page.locator('.story-visual img').all()){await img.scrollIntoViewIfNeeded();await img.evaluate(e=>e.loading='eager');await page.waitForFunction(()=>Array.from(document.querySelectorAll('.story-visual img')).every(e=>e.complete&&e.naturalWidth>0));await img.evaluate(e=>e.decode());assert.ok((await img.getAttribute('alt')).length>30);}});
 await check(file+' disclosures work with keyboard',async()=>{for(const d of await page.locator('details').all()){if(!(await d.locator(':scope > summary').isVisible()))continue;await d.evaluate(e=>{for(let p=e.parentElement;p;p=p.parentElement)if(p.tagName==='DETAILS')p.open=true;e.open=false;});if(!(await d.locator(':scope > summary').isVisible()))continue;await d.locator(':scope > summary').focus();await page.keyboard.press('Enter');assert.ok(await d.evaluate(e=>e.open));}});
 if(['professional.html','engineering.html','quality.html','process.html','context.html','systems.html','responsibility.html'].includes(file)) await check(file+' guided attempt and revision feedback',async()=>{assert.equal(await page.locator('.guiding-question').count(),1);assert.equal(await page.locator('.answer-contrast article').count(),2);await page.locator('#topic-response').fill('A stakeholder, an uncertainty and observable evidence.');await page.locator('.micro-feedback').evaluate(e=>e.open=false);await page.locator('.micro-feedback summary').click();assert.ok(await page.locator('.micro-feedback').evaluate(e=>e.open));assert.match(await page.locator('.micro-feedback').innerText(),/Revise:/);});
 for(const width of [320,390,768,980,981,1440]){await page.setViewportSize({width,height:900});await check(file+' reflow '+width,async()=>{const d=await page.evaluate(()=>({w:innerWidth,s:document.documentElement.scrollWidth}));assert.ok(d.s<=d.w,JSON.stringify(d))});}
 for(const width of [390,1440]){await page.setViewportSize({width,height:900});await page.screenshot({path:path.join(out,file+'-'+width+'.png'),fullPage:true});}
}
await page.setViewportSize({width:390,height:844});await page.goto(base+root+'quality.html');
await check('mobile topic menu opens and selects another topic',async()=>{const m=page.locator('.unit-menu');assert.equal(await m.evaluate(e=>e.open),false);await m.locator('summary').click();assert.ok(await m.evaluate(e=>e.open));await page.locator('.unit-menu a[href="process.html"]').click();await page.waitForURL('**/process.html');assert.equal(await page.locator('[aria-current="page"].unit-nav-link').getAttribute('href'),'process.html');});
await check('mobile content and navigation stay compact',async()=>{await page.goto(base+root+'engineering.html');assert.equal(await page.locator('.course-menu').evaluate(e=>e.open),false);assert.equal(await page.locator('.unit-menu').evaluate(e=>e.open),false);assert.equal(await page.locator('.type-legend').isVisible(),false);const h=await page.locator('h1').boundingBox();assert.ok(h.y<280,'Heading should appear near the start of the first mobile screen');await page.locator('.course-menu summary').click();assert.ok(await page.locator('.site-nav').isVisible());await page.locator('.course-menu summary').click();});
await check('core route bypasses supporting reading and uses semantic labels',async()=>{await page.goto(base+root+'process.html');assert.equal(await page.locator('.page-turn a').last().getAttribute('href'),'systems.html');assert.equal(await page.locator('.visual>.content-badge.kind-theory').count(),2);await page.goto(base+root+'quality.html');assert.equal(await page.locator('.visual>.content-badge.kind-theory').count(),1);await page.goto(base+root);assert.equal(await page.locator('.journey-stages article').count(),4);assert.equal(await page.locator('#storyline').count(),1);});
await check('legacy quality URL redirects to topic',async()=>{await page.goto(base+root+'#quality');await page.waitForURL('**/quality.html#quality');});
await page.goto(base+root+'workshop.html');
await check('workshop notes export retains entered text',async()=>{assert.equal(await page.locator('[data-worksheet]').count(),10);await page.locator('#risk-1-symptom').fill('E1 confirmation and stored record differ');const pending=page.waitForEvent('download');await page.locator('#u01-download-notes').click();const d=await pending;await d.saveAs(path.join(out,'workshop.txt'));assert.ok(fs.readFileSync(path.join(out,'workshop.txt'),'utf8').includes('E1 confirmation'));});
await page.goto(base+root+'transfer.html');await check('individual response export',async()=>{await page.locator('#u01-exit-response').fill('Stakeholder. Risk and uncertainty. Observable evidence.');const pending=page.waitForEvent('download');await page.locator('#u01-download-exit').click();const d=await pending;await d.saveAs(path.join(out,'exit.txt'));assert.ok(fs.readFileSync(path.join(out,'exit.txt'),'utf8').includes('Observable evidence.'));});
await page.goto(base+root+'practice.html');await check('five quiz questions answer, lock and reset',async()=>{const qs=page.locator('.quiz-q');assert.equal(await qs.count(),5);for(const q of await qs.all()){const a=await q.getAttribute('data-answer');await q.locator(`[data-choice="${a}"]`).click();assert.equal(await q.getAttribute('data-correct'),'true');await q.locator('.u01-reset').click();assert.equal(await q.getAttribute('data-attempted'),'false');}});
await check('instructor notes moved out of student pages',async()=>{assert.equal(await page.locator('[data-instructor-only]').count(),0);await page.goto(base+root+'instructor.html');assert.equal(await page.locator('.instructor-note').count(),2);});
await check('skip link focuses main',async()=>{await page.goto(base+root);await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement.className),'skip');await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>document.activeElement.id),'main');});
const nojs=await browser.newPage({javaScriptEnabled:false,ignoreHTTPSErrors:process.env.PROXY_TLS_INTERCEPTION==='1',viewport:{width:390,height:844}});if(process.env.BLOCK_EXTERNAL_FONTS==='1'){await nojs.route('https://fonts.googleapis.com/**',r=>r.abort());await nojs.route('https://fonts.gstatic.com/**',r=>r.abort());}await nojs.goto(base+root+'practice.html',{waitUntil:'networkidle'});await check('no-JavaScript navigation and practice reasoning',async()=>{assert.ok(await nojs.locator('.unit-menu a[href="quality.html"]').isVisible());assert.equal(await nojs.locator('.quiz-feedback:visible').count(),5);});await nojs.close();
await check('no uncaught JavaScript errors',()=>assert.deepEqual(errors,[]));
fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({url:base+root,revision:'20261009-focus2',date:new Date().toISOString(),browser:browser.version(),completed:true,tlsCertificateValidation:process.env.PROXY_TLS_INTERCEPTION!=='1',externalFontsBlocked:process.env.BLOCK_EXTERNAL_FONTS==='1',checks,errors},null,2));console.log(JSON.stringify({passed:checks.filter(c=>c.passed).length,failed:checks.filter(c=>!c.passed)},null,2));await browser.close();process.exitCode=checks.some(c=>!c.passed)?1:0;
})().catch(async e=>{fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({completed:false,checks,errors,fatal:e.message},null,2));console.error(e.message);if(activeBrowser)await activeBrowser.close().catch(()=>{});process.exitCode=1});
