(()=>{
  if(sessionStorage.getItem('cpcs351_access')!=='granted'){window.location.href='../../access.html';return;}
  const $=(s,r=document)=>r.querySelector(s); const $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const topicKey=()=>`cpcs351-topic-${Number(document.body.dataset.topic||0)}`; const safeText=s=>(s||'').replace(/\s+/g,' ').trim();
  const icon=name=>{const p={search:'<circle cx="11" cy="11" r="6"></circle><path d="m16 16 4 4"></path>',up:'<path d="m6 14 6-6 6 6"></path>',left:'<path d="m15 18-6-6 6-6"></path>',right:'<path d="m9 18 6-6-6-6"></path>',check:'<path d="m5 12 4 4L19 6"></path>'};return `<span class="ui-icon" aria-hidden="true"><svg viewBox="0 0 24 24">${p[name]||''}</svg></span>`};
  function injectDesignSystem(){if(document.querySelector('link[data-cpcs351-design-system]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='../../design-system.css';l.dataset.cpcs351DesignSystem='true';document.head.append(l)}
  function a11y(){if(!$('#skip-link')){const a=document.createElement('a');a.id='skip-link';a.className='skip-link';a.href='#main-study-content';a.textContent='Skip to learning content';document.body.prepend(a)}const m=$('main');if(m){m.id='main-study-content';m.tabIndex=-1}$$('iframe').forEach((f,i)=>{if(!f.title)f.title=`External learning reference ${i+1}`;f.loading='lazy'});$$('img').forEach(img=>{if(!img.hasAttribute('alt'))img.alt='';if(!img.closest('.hero'))img.loading=img.loading||'lazy';img.decoding='async'});$$('a[href]').forEach(a=>{const h=a.getAttribute('href');if(h&&/^https?:/i.test(h)){a.target='_blank';a.rel='noopener noreferrer'}})}
  function normalizeStructure(){const c=$('.content'),h=$('.hero');if(!c||!h)return;const t=String(document.body.dataset.topic||'').padStart(2,'0'),h1=safeText($('.hero h1')?.textContent||document.title.split('|')[0]);if(!$('.breadcrumb')){const b=document.createElement('div');b.className='breadcrumb';b.innerHTML=`<a href="../../index.html">CPCS 351</a><span>›</span><span>Topic ${t}</span><span>›</span><span>${h1}</span>`;c.insertBefore(b,h)}if(!$('.study-key')){const k=document.createElement('div');k.className='study-key';k.innerHTML='<span><i class="dot core"></i> Core Lecture Content</span><span><i class="dot add"></i> Added Study Material</span>';h.insertAdjacentElement('afterend',k)}}
  function normalizeNavigation(){const s=$('.sidebar');if(!s)return;const links=$$('.side-link,.side-nav a',s);links.forEach(a=>a.classList.add('side-link'));const cur=links.find(a=>a.classList.contains('active'))||links.find(a=>new URL(a.href,location.href).pathname===location.pathname);links.forEach(a=>{a.classList.toggle('active',a===cur);a===cur?a.setAttribute('aria-current','page'):a.removeAttribute('aria-current')});let mobile=$('.mobile-topic');if(!mobile&&links.length){mobile=document.createElement('nav');mobile.className='mobile-topic';const shell=$('.shell');shell?.parentNode.insertBefore(mobile,shell)}if(mobile&&links.length){mobile.innerHTML='';mobile.setAttribute('aria-label','Topic lessons');links.forEach((a,i)=>{const m=document.createElement('a');m.href=a.getAttribute('href');m.className=a===cur?'active':'';const label=safeText(a.textContent).replace(/✓$/,'').trim();m.textContent=label.match(/^\d{2}/)?label:`${String(i+1).padStart(2,'0')} ${label}`;if(a===cur)m.setAttribute('aria-current','page');mobile.append(m)})}}
  function progress(){const hero=$('.hero');if(!hero)return;const page=Number(document.body.dataset.page||1),nav=$$('.side-link,.side-nav a'),total=Math.max(nav.length,Number(($('.hero-progress small')?.textContent.match(/of\s+(\d+)/i)||[])[1]||1));let store={};try{store=JSON.parse(localStorage.getItem(topicKey())||'{}')}catch{}const done=new Set(store.completed||[]),bar=document.createElement('section');bar.className='learning-progress';bar.setAttribute('aria-label','Learning progress');bar.innerHTML=`<div class="progress-copy"><strong>Topic Progress</strong><span aria-live="polite"></span></div><div class="progress-track" role="progressbar" aria-valuemin="0" aria-valuemax="${total}" aria-valuenow="0"><i></i></div><button class="complete-btn" type="button"></button>`;hero.insertAdjacentElement('afterend',bar);const st=$('.progress-copy span',bar),tr=$('.progress-track',bar),fill=$('.progress-track i',bar),btn=$('.complete-btn',bar);function render(){const n=done.size;st.textContent=`${n} of ${total} pages completed`;tr.setAttribute('aria-valuenow',String(n));fill.style.width=`${Math.min(100,n/total*100)}%`;const d=done.has(page);btn.classList.toggle('is-complete',d);btn.innerHTML=d?`${icon('check')}<span>Completed</span>`:'<span>Mark Page Complete</span>';btn.setAttribute('aria-pressed',String(d));nav.forEach((a,i)=>a.classList.toggle('is-complete',done.has(i+1)))}btn.addEventListener('click',()=>{done.has(page)?done.delete(page):done.add(page);localStorage.setItem(topicKey(),JSON.stringify({completed:[...done].sort((a,b)=>a-b)}));render()});render()}
  function normalizeTerminology(){$$('.course-home,.home-link').forEach(el=>el.textContent='Course Home');const p=$('.lesson-nav .prev,#prev-link'),n=$('.lesson-nav .next,#next-link');if(p){p.innerHTML=`${icon('left')}<span>Previous Lesson</span>`;p.setAttribute('aria-label','Previous lesson')}if(n){const topic=/Next Topic/i.test(n.textContent);n.innerHTML=`<span>${topic?'Next Topic':'Next Lesson'}</span>${icon('right')}`;n.setAttribute('aria-label',topic?'Next topic':'Next lesson')}}
  function removeDeprecatedBlocks(){$$('.active-recall,.feedback-note').forEach(el=>el.remove());$$('.enrichment').forEach(el=>{const t=safeText(el.textContent);if(/Ask yourself.*Exam lens/i.test(t))el.remove()})}
  function tools(){if($('#study-tools'))return;const p=document.createElement('div');p.id='study-tools';p.className='study-tools';p.innerHTML=`<button type="button" data-action="search">${icon('search')}<span>Find</span></button><button type="button" data-action="top">${icon('up')}<span>Top</span></button>`;p.style.cssText='left:12px!important;right:auto!important;bottom:12px!important;width:max-content!important;max-width:236px!important;min-width:0!important;display:inline-flex!important;align-items:center!important;gap:4px!important;padding:5px!important;border-radius:14px!important;';$$('button',p).forEach(b=>{b.style.cssText='min-width:0!important;min-height:36px!important;padding:6px 9px!important;border-radius:10px!important;font-size:11px!important;gap:5px!important;'});document.body.append(p);$('[data-action="top"]',p).addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'}));$('[data-action="search"]',p).addEventListener('click',()=>{const q=prompt('Find on this page:');if(q)window.find?.(q)})}
  injectDesignSystem();window.addEventListener('DOMContentLoaded',()=>setTimeout(()=>{removeDeprecatedBlocks();a11y();normalizeStructure();normalizeNavigation();progress();normalizeTerminology();tools();document.body.classList.add('enhanced-study');$('.mobile-topic .active')?.scrollIntoView({inline:'center',block:'nearest'})},0));
})();