'use strict';
const SUPABASE_URL='https://obgmbgsgwxbenglltcwv.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_Qa-0cZ5V15zHHYIWD_SXcA_yCZ0N2GM';
const LIVE_SESSION_ROLES=[window.RoleAccess.ROLES.ADMINISTRATOR,window.RoleAccess.ROLES.INSTRUCTOR,window.RoleAccess.ROLES.TEACHING_ASSISTANT];
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
const $=id=>document.getElementById(id),show=el=>el?.classList.remove('is-hidden'),hide=el=>el?.classList.add('is-hidden');
let currentSession=null,roster=[],clockTimer=null,rosterTimer=null,rosterLoading=false;
const msg=(el,text='',type='')=>{if(el){el.textContent=text;el.className=`live-message ${type}`.trim();}};
const fmtTime=v=>v?new Intl.DateTimeFormat('ar-SA',{hour:'2-digit',minute:'2-digit',hour12:true,timeZone:'Asia/Riyadh'}).format(new Date(v)):'—';
const fmtDate=v=>v?new Intl.DateTimeFormat('ar-SA',{weekday:'long',year:'numeric',month:'long',day:'numeric',timeZone:'Asia/Riyadh'}).format(new Date(v)):'—';
const fmtRecorded=v=>v?new Intl.DateTimeFormat('ar-SA',{hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:true,timeZone:'Asia/Riyadh'}).format(new Date(v)):'—';
const modeAr=v=>({InPerson:'حضوري',Online:'أونلاين',Hybrid:'هجين'}[v]||v||'—');
const statusAr=v=>({Present:'حاضر',Late:'متأخر',Absent:'غائب',Unmarked:'لم يسجل'}[v]||'لم يسجل');
const sourceAr=v=>({NFC:'بطاقة NFC',Manual:'يدوي',System:'النظام'}[v]||'—');
async function rpc(name,params={}){const{data,error}=await db.rpc(name,params);if(error)throw new Error(error.message||'تعذر تنفيذ العملية.');return data;}
async function verifyAdmin(){return Boolean(await window.RoleAccess.requireRole(db,LIVE_SESSION_ROLES,'./'));}
function updateClock(){if(!currentSession)return;const now=Date.now(),start=new Date(currentSession.start_time).getTime(),end=new Date(currentSession.end_time).getTime();let diff,label;if(now<start){diff=start-now;label='تبدأ بعد';}else if(now<=end){diff=now-start;label='بدأت منذ';}else{diff=now-end;label='انتهت منذ';}const t=Math.floor(diff/1000),h=Math.floor(t/3600),m=Math.floor((t%3600)/60),s=t%60;$('clockLabel').textContent=label;$('sessionClock').textContent=`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;}
function renderSession(s){currentSession=s;hide($('loadingView'));if(!s){show($('emptyView'));hide($('liveView'));return;}hide($('emptyView'));show($('liveView'));$('courseCode').textContent=s.course_code||'—';$('sessionSummary').textContent=`${fmtDate(s.start_time)} — ${s.room||'دون قاعة'}`;$('room').textContent=s.room||'—';$('sessionTime').textContent=`${fmtTime(s.start_time)} - ${fmtTime(s.end_time)}`;$('deliveryMode').textContent=modeAr(s.delivery_mode);$('attendanceRequired').textContent=s.attendance_required?'محتسبة':'غير محتسبة';const b=$('sessionStatusBadge'),cancel=s.schedule_status==='Cancelled',closed=!s.is_active&&new Date(s.end_time)<new Date();if(cancel){$('sessionEyebrow').textContent='محاضرة ملغاة';b.textContent='ملغاة';b.className='live-badge cancelled';}else if(s.is_active){$('sessionEyebrow').textContent='الجلسة النشطة';b.textContent='التحضير مفتوح';b.className='live-badge active';}else if(closed){$('sessionEyebrow').textContent='آخر محاضرة';b.textContent='منتهية';b.className='live-badge closed';}else{$('sessionEyebrow').textContent='المحاضرة القادمة';b.textContent='جاهزة';b.className='live-badge ready';}$('startSessionButton').classList.toggle('is-hidden',s.is_active||cancel||closed);$('closeSessionButton').classList.toggle('is-hidden',!s.is_active);updateClock();clearInterval(clockTimer);clockTimer=setInterval(updateClock,1000);}
function renderStats(){const summary=window.LiveSessionCalculations.summarizeRoster(roster),last=summary.last_attendee;$('studentCount').textContent=summary.student_count;$('presentCount').textContent=summary.present_count;$('lateCount').textContent=summary.late_count;$('absentCount').textContent=summary.absent_count;$('unmarkedCount').textContent=summary.unmarked_count;$('attendancePercentage').textContent=`${summary.attendance_percentage.toFixed(1)}%`;$('lastAttendee').textContent=last?.student_name||'—';$('lastAttendeeTime').textContent=last?fmtRecorded(last.recorded_at):'—';}
function renderRoster(){const q=$('studentSearch').value.trim().toLowerCase(),rows=roster.filter(x=>!q||String(x.university_id).toLowerCase().includes(q)||String(x.student_name).toLowerCase().includes(q));$('rosterTableBody').innerHTML='';hide($('rosterLoading'));if(!rows.length){show($('rosterEmpty'));hide($('rosterTableWrap'));renderStats();return;}hide($('rosterEmpty'));show($('rosterTableWrap'));rows.forEach(x=>{const tr=document.createElement('tr');[x.university_id,x.student_name].forEach(v=>{const td=document.createElement('td');td.textContent=v;tr.appendChild(td);});const st=document.createElement('td'),sb=document.createElement('span'),status=x.attendance_status||'Unmarked';sb.className=`status-pill ${status.toLowerCase()}`;sb.textContent=statusAr(status);st.appendChild(sb);tr.appendChild(st);const so=document.createElement('td'),source=document.createElement('span');source.className='source-pill';source.textContent=sourceAr(x.attendance_source);so.appendChild(source);tr.appendChild(so);const time=document.createElement('td');time.textContent=fmtRecorded(x.recorded_at);tr.appendChild(time);const action=document.createElement('td'),btn=document.createElement('button');btn.className='manual-button';btn.type='button';btn.textContent=status==='Unmarked'?'تحضير يدوي':'تعديل';btn.onclick=()=>openManual(x);action.appendChild(btn);tr.appendChild(action);$('rosterTableBody').appendChild(tr);});renderStats();}
async function loadRoster({silent=false}={}){if(!currentSession||rosterLoading)return;rosterLoading=true;if(!silent){show($('rosterLoading'));hide($('rosterEmpty'));hide($('rosterTableWrap'));}$('connectionLabel').textContent='جارٍ التحديث...';try{const rows=await rpc('admin_get_live_roster',{p_session_id:currentSession.session_id});roster=Array.isArray(rows)?rows:[];renderRoster();$('connectionLabel').textContent='محدّث مباشرة';}catch(e){if(!silent){hide($('rosterLoading'));show($('rosterEmpty'));$('rosterEmpty').textContent=e.message;}$('connectionLabel').textContent='تعذر التحديث';}finally{rosterLoading=false;}}
function startRosterUpdates(){clearInterval(rosterTimer);rosterTimer=setInterval(()=>{if(!document.hidden)loadRoster({silent:true});},5000);}
async function loadLive(){show($('loadingView'));hide($('emptyView'));hide($('liveView'));try{const data=await rpc('admin_get_relevant_session'),s=Array.isArray(data)?data[0]:data;renderSession(s||null);if(s)await loadRoster();}catch(e){hide($('loadingView'));show($('emptyView'));$('emptyView').querySelector('h1').textContent='تعذر تحميل المحاضرة';$('emptyView').querySelector('p').textContent=e.message;}}
async function startSession(){if(!currentSession||!confirm('فتح التحضير لهذه المحاضرة الآن؟'))return;try{await rpc('admin_activate_session',{p_session_id:currentSession.session_id});await loadLive();}catch(e){alert(e.message);}}
async function closeSession(){if(!currentSession||!confirm('إغلاق التحضير لهذه المحاضرة؟'))return;try{await rpc('admin_close_session',{p_session_id:currentSession.session_id});await loadLive();}catch(e){alert(e.message);}}
function openManual(x){$('manualStudentId').value=x.university_id;$('manualStudentName').textContent=`${x.student_name} — ${x.university_id}`;$('manualStatus').value=x.attendance_status&&x.attendance_status!=='Unmarked'?x.attendance_status:'Present';$('manualReason').value='';msg($('manualMessage'));$('manualDialog').showModal();}
$('manualForm').onsubmit=async e=>{e.preventDefault();const reason=$('manualReason').value.trim();if(!reason){msg($('manualMessage'),'اكتب سبب التحضير أو التعديل اليدوي.','error');return;}$('saveManualButton').disabled=true;try{await rpc('admin_set_manual_attendance',{p_session_id:currentSession.session_id,p_university_id:$('manualStudentId').value,p_status:$('manualStatus').value,p_reason:reason});msg($('manualMessage'),'تم حفظ التعديل.','success');setTimeout(async()=>{$('manualDialog').close();await loadRoster();},500);}catch(err){msg($('manualMessage'),err.message,'error');}finally{$('saveManualButton').disabled=false;}};
function updateExceptionFields(){$('exceptionRoomField').classList.toggle('is-hidden',$('exceptionAction').value!=='ROOM');}
$('exceptionForm').onsubmit=async e=>{e.preventDefault();const action=$('exceptionAction').value,room=$('exceptionRoom').value.trim();if(action==='ROOM'&&!room){msg($('exceptionMessage'),'أدخل القاعة الجديدة.','error');return;}$('saveExceptionButton').disabled=true;try{await rpc('admin_apply_session_exception',{p_session_id:currentSession.session_id,p_action:action,p_room:room||null,p_reason:$('exceptionReason').value.trim()||null});msg($('exceptionMessage'),'تم تطبيق الاستثناء.','success');setTimeout(async()=>{$('exceptionDialog').close();await loadLive();},500);}catch(err){msg($('exceptionMessage'),err.message,'error');}finally{$('saveExceptionButton').disabled=false;}};
$('startSessionButton').onclick=startSession;$('closeSessionButton').onclick=closeSession;$('refreshRosterButton').onclick=()=>loadRoster();$('studentSearch').oninput=renderRoster;$('editExceptionButton').onclick=()=>{$('exceptionAction').value='ROOM';$('exceptionRoom').value=currentSession?.room||'';$('exceptionReason').value='';updateExceptionFields();msg($('exceptionMessage'));$('exceptionDialog').showModal();};$('exceptionAction').onchange=updateExceptionFields;$('closeManualDialog').onclick=()=>$('manualDialog').close();$('closeExceptionDialog').onclick=()=>$('exceptionDialog').close();document.addEventListener('visibilitychange',()=>{if(!document.hidden)loadRoster({silent:true});});window.addEventListener('beforeunload',()=>{clearInterval(rosterTimer);clearInterval(clockTimer);});(async()=>{if(await verifyAdmin()){await loadLive();startRosterUpdates();}})();
