begin;

create table if not exists public.attendance_notifications (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.users(id) on delete cascade,
  notification_type text not null,
  title_ar text not null,
  message_ar text not null,
  related_course_code text,
  related_session_id text references public.sessions(id) on delete set null,
  is_read boolean not null default false,
  created_at timestamptz not null default now(),
  read_at timestamptz,
  constraint attendance_notifications_type_check check (
    notification_type in (
      'AttendanceChanged',
      'ExcuseAccepted',
      'ExcuseRejected',
      'ExcuseMoreInfo',
      'DenialRisk'
    )
  ),
  constraint attendance_notifications_message_check check (
    char_length(title_ar) between 2 and 120
    and char_length(message_ar) between 2 and 1000
  )
);

create index if not exists attendance_notifications_student_created_idx
  on public.attendance_notifications (student_id, created_at desc);
create index if not exists attendance_notifications_unread_idx
  on public.attendance_notifications (student_id, is_read)
  where not is_read;

alter table public.attendance_notifications enable row level security;
revoke all on public.attendance_notifications from anon, authenticated;
grant select, update on public.attendance_notifications to authenticated;

drop policy if exists attendance_notifications_student_select
  on public.attendance_notifications;
create policy attendance_notifications_student_select
  on public.attendance_notifications
  for select to authenticated
  using (
    student_id = auth.uid()
    or public.attendance_is_privileged()
  );

drop policy if exists attendance_notifications_student_update
  on public.attendance_notifications;
create policy attendance_notifications_student_update
  on public.attendance_notifications
  for update to authenticated
  using (student_id = auth.uid())
  with check (student_id = auth.uid());

create table if not exists public.attendance_retention_policies (
  data_category text primary key,
  retention_days integer not null,
  archive_before_delete boolean not null default true,
  legal_basis_ar text not null,
  is_enabled boolean not null default true,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id),
  constraint attendance_retention_days_check
    check (retention_days between 30 and 3650)
);

insert into public.attendance_retention_policies (
  data_category, retention_days, archive_before_delete, legal_basis_ar
) values
  ('attendance_logs', 1825, true, 'السجل الأكاديمي وإثبات الحضور'),
  ('excuse_requests', 1825, true, 'القرار الأكاديمي ومراجعة الاعتراض'),
  ('audit_events', 2555, true, 'المساءلة والأمن والتحقيق في الحوادث'),
  ('pilot_checks', 730, true, 'إثبات التحقق قبل التعميم'),
  ('login_challenges', 30, false, 'أمن الدخول وتقليل البيانات')
on conflict (data_category) do nothing;

alter table public.attendance_retention_policies enable row level security;
revoke all on public.attendance_retention_policies from anon, authenticated;
grant select on public.attendance_retention_policies to authenticated;

drop policy if exists attendance_retention_privileged_select
  on public.attendance_retention_policies;
create policy attendance_retention_privileged_select
  on public.attendance_retention_policies
  for select to authenticated
  using (public.attendance_is_privileged());

create table if not exists public.attendance_term_archives (
  archive_id bigint generated by default as identity primary key,
  term_code text not null,
  archive_status text not null default 'Completed',
  archived_at timestamptz not null default now(),
  archived_by uuid not null references auth.users(id),
  course_count integer not null,
  session_count integer not null,
  attendance_count integer not null,
  excuse_count integer not null,
  snapshot jsonb not null,
  constraint attendance_term_archive_status_check check (
    archive_status in ('Completed', 'Verified', 'Superseded')
  ),
  constraint attendance_term_archive_unique unique (term_code, archived_at)
);

create index if not exists attendance_term_archives_term_idx
  on public.attendance_term_archives (term_code, archived_at desc);

alter table public.attendance_term_archives enable row level security;
revoke all on public.attendance_term_archives from anon, authenticated;
grant select on public.attendance_term_archives to authenticated;

drop policy if exists attendance_term_archives_privileged_select
  on public.attendance_term_archives;
create policy attendance_term_archives_privileged_select
  on public.attendance_term_archives
  for select to authenticated
  using (public.attendance_is_privileged());

create or replace function public.attendance_enqueue_change_notification()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  course_value text;
begin
  if tg_table_name = 'excuse_requests'
     and old.status is distinct from new.status then
    select s.course_code
      into course_value
      from public.sessions s
     where s.id = new.session_id;

    insert into public.attendance_notifications (
      student_id,
      notification_type,
      title_ar,
      message_ar,
      related_course_code,
      related_session_id
    ) values (
      new.student_id,
      case new.status
        when 'Accepted' then 'ExcuseAccepted'
        when 'Rejected' then 'ExcuseRejected'
        else 'ExcuseMoreInfo'
      end,
      case new.status
        when 'Accepted' then 'تم قبول العذر'
        when 'Rejected' then 'تم رفض العذر'
        else 'العذر يحتاج معلومات إضافية'
      end,
      case new.status
        when 'Accepted' then 'اعتمد العذر وأعيد احتساب سجل حضورك.'
        when 'Rejected' then 'رُفض العذر. راجع ملاحظة المعلم في سجل الحضور.'
        else 'أضف المعلومات المطلوبة لإكمال مراجعة العذر.'
      end,
      course_value,
      new.session_id
    );
  elsif tg_table_name = 'attendance_logs'
        and old.status is distinct from new.status then
    insert into public.attendance_notifications (
      student_id,
      notification_type,
      title_ar,
      message_ar,
      related_course_code,
      related_session_id
    ) values (
      new.student_id,
      'AttendanceChanged',
      'تغيّر سجل الحضور',
      'تم تحديث حالة حضورك في المقرر ' || coalesce(new.course_code, '—') ||
        ' من ' || coalesce(old.status, '—') || ' إلى ' || coalesce(new.status, '—') || '.',
      new.course_code,
      new.session_id
    );
  end if;
  return new;
end;
$$;

drop trigger if exists excuse_request_notification
  on public.excuse_requests;
create trigger excuse_request_notification
after update of status on public.excuse_requests
for each row
when (old.status is distinct from new.status)
execute function public.attendance_enqueue_change_notification();

drop trigger if exists attendance_log_change_notification
  on public.attendance_logs;
create trigger attendance_log_change_notification
after update of status on public.attendance_logs
for each row
when (old.status is distinct from new.status)
execute function public.attendance_enqueue_change_notification();

create or replace function public.get_my_attendance_notifications(
  p_limit integer default 30
)
returns jsonb
language sql
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'success', true,
    'unread_count', count(*) filter (where not is_read),
    'notifications', coalesce(
      jsonb_agg(
        jsonb_build_object(
          'id', id,
          'type', notification_type,
          'title', title_ar,
          'message', message_ar,
          'course_code', related_course_code,
          'session_id', related_session_id,
          'is_read', is_read,
          'created_at', created_at
        )
        order by created_at desc
      ),
      '[]'::jsonb
    )
  )
  from (
    select *
    from public.attendance_notifications
    where student_id = auth.uid()
    order by created_at desc
    limit least(greatest(coalesce(p_limit, 30), 1), 100)
  ) n;
$$;

revoke all on function public.get_my_attendance_notifications(integer)
  from public;
grant execute on function public.get_my_attendance_notifications(integer)
  to authenticated;

create or replace function public.admin_get_institutional_attendance_report(
  p_term_code text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.attendance_is_privileged() then
    raise exception 'غير مصرح بعرض التقرير المؤسسي'
      using errcode = '42501';
  end if;

  return (
    with report as (
      select
        cp.term_code,
        cp.course_code,
        cp.course_name,
        cp.section_code,
        count(distinct s.id) as session_count,
        count(a.id) as attendance_records,
        count(a.id) filter (where lower(a.status) = 'present') as present_count,
        count(a.id) filter (where lower(a.status) = 'late') as late_count,
        count(a.id) filter (where lower(a.status) = 'absent') as absent_count,
        count(distinct a.student_id) as participating_students
      from public.course_plans cp
      left join public.sessions s on s.course_plan_id = cp.id
      left join public.attendance_logs a on a.session_id = s.id
      where p_term_code is null or cp.term_code = p_term_code
      group by cp.term_code, cp.course_code, cp.course_name, cp.section_code
    )
    select jsonb_build_object(
      'success', true,
      'generated_at', now(),
      'term_code', p_term_code,
      'summary', jsonb_build_object(
        'courses', count(*),
        'sessions', coalesce(sum(session_count), 0),
        'students', coalesce(sum(participating_students), 0),
        'attendance_records', coalesce(sum(attendance_records), 0)
      ),
      'rows', coalesce(jsonb_agg(to_jsonb(report) order by term_code, course_code, section_code), '[]'::jsonb)
    )
    from report
  );
end;
$$;

revoke all on function public.admin_get_institutional_attendance_report(text)
  from public;
grant execute on function public.admin_get_institutional_attendance_report(text)
  to authenticated;

create or replace function public.admin_preview_attendance_retention()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.attendance_is_privileged() then
    raise exception 'غير مصرح بعرض سياسة الاحتفاظ'
      using errcode = '42501';
  end if;

  return jsonb_build_object(
    'success', true,
    'preview_only', true,
    'generated_at', now(),
    'categories', jsonb_build_array(
      jsonb_build_object(
        'category', 'attendance_logs',
        'eligible_rows', (
          select count(*)
          from public.attendance_logs
          where created_at < now() - (
            select make_interval(days => retention_days)
            from public.attendance_retention_policies
            where data_category = 'attendance_logs'
          )
        )
      ),
      jsonb_build_object(
        'category', 'excuse_requests',
        'eligible_rows', (
          select count(*)
          from public.excuse_requests
          where submitted_at < now() - (
            select make_interval(days => retention_days)
            from public.attendance_retention_policies
            where data_category = 'excuse_requests'
          )
        )
      ),
      jsonb_build_object(
        'category', 'login_challenges',
        'eligible_rows', (
          select count(*)
          from public.student_login_challenges
          where requested_at < now() - (
            select make_interval(days => retention_days)
            from public.attendance_retention_policies
            where data_category = 'login_challenges'
          )
        )
      )
    )
  );
end;
$$;

revoke all on function public.admin_preview_attendance_retention()
  from public;
grant execute on function public.admin_preview_attendance_retention()
  to authenticated;

create or replace function public.admin_archive_attendance_term(
  p_term_code text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  archive_row public.attendance_term_archives%rowtype;
begin
  if not public.attendance_is_privileged() then
    raise exception 'غير مصرح بأرشفة الفصل'
      using errcode = '42501';
  end if;
  if nullif(trim(p_term_code), '') is null then
    raise exception 'رمز الفصل مطلوب';
  end if;

  insert into public.attendance_term_archives (
    term_code,
    archived_by,
    course_count,
    session_count,
    attendance_count,
    excuse_count,
    snapshot
  )
  select
    p_term_code,
    auth.uid(),
    (select count(*) from public.course_plans where term_code = p_term_code),
    (
      select count(*)
      from public.sessions s
      join public.course_plans cp on cp.id = s.course_plan_id
      where cp.term_code = p_term_code
    ),
    (
      select count(*)
      from public.attendance_logs a
      join public.sessions s on s.id = a.session_id
      join public.course_plans cp on cp.id = s.course_plan_id
      where cp.term_code = p_term_code
    ),
    (
      select count(*)
      from public.excuse_requests e
      join public.sessions s on s.id = e.session_id
      join public.course_plans cp on cp.id = s.course_plan_id
      where cp.term_code = p_term_code
    ),
    jsonb_build_object(
      'course_plans', coalesce((
        select jsonb_agg(to_jsonb(cp) order by cp.course_code, cp.section_code)
        from public.course_plans cp
        where cp.term_code = p_term_code
      ), '[]'::jsonb),
      'report', public.admin_get_institutional_attendance_report(p_term_code)
    )
  returning * into archive_row;

  return jsonb_build_object(
    'success', true,
    'archive_id', archive_row.archive_id,
    'term_code', archive_row.term_code,
    'archived_at', archive_row.archived_at,
    'counts', jsonb_build_object(
      'courses', archive_row.course_count,
      'sessions', archive_row.session_count,
      'attendance', archive_row.attendance_count,
      'excuses', archive_row.excuse_count
    )
  );
end;
$$;

revoke all on function public.admin_archive_attendance_term(text)
  from public;
grant execute on function public.admin_archive_attendance_term(text)
  to authenticated;

commit;
