const TOPIC09=[['index.html','Behavioral Modeling: The Big Picture'],['state-foundations.html','Object State Modeling Foundations'],['state-notation.html','States, Events, Transitions & Guards'],['state-examples.html','Progressive State Machine Examples'],['state-advanced.html','Composite States & Design Steps'],['activity-foundations.html','Activity Modeling Foundations'],['notations.html','Activity Notation & Decisions'],['concurrency.html','Fork, Join & Object Flow'],['swimlanes.html','Swimlanes & Responsibility'],['orders-supply.html','Worked Workflow Example'],['extra-examples.html','Activity Diagram Practice Studio'],['choose-model.html','Choosing State, Activity or Sequence'],['review.html','Integrated Behavioral Modeling Review']];

const T9_HOOKS={
1:{icon:'🧭',title:'Three lenses on dynamic behavior',html:'<div class="t9-compare"><div class="t9-model"><b>Sequence</b><small>Who communicates with whom?</small><p>Interaction across participants over time.</p></div><div class="t9-model"><b>State</b><small>How does one object react?</small><p>Lifetime, events, states and transitions.</p></div><div class="t9-model"><b>Activity</b><small>How does work flow?</small><p>Actions, decisions, concurrency and responsibility.</p></div></div>'},
2:{icon:'🎛️',title:'Reactive object mental model',html:'<div class="t9-flow"><div class="t9-node"><strong>External stimulus</strong>event happens</div><div class="t9-arrow">→</div><div class="t9-node"><strong>Current state</strong>context now</div><div class="t9-arrow">→</div><div class="t9-node"><strong>Reaction</strong>state-dependent response</div><div class="t9-arrow">→</div><div class="t9-node"><strong>New state</strong>updated condition</div></div>'},
3:{icon:'⚡',title:'Event drives a transition',html:'<div class="t9-state-track"><div class="t9-state">Available</div><div class="t9-event"><span>→</span>borrow [allowed]</div><div class="t9-state">Borrowed</div><div class="t9-event"><span>→</span>return</div><div class="t9-state">Available</div></div>'},
4:{icon:'🚦',title:'Progress from simple to richer lifecycles',html:'<div class="t9-grid"><div class="t9-mini"><b>1 · Food Delivery Order</b>Basic lifecycle, events and alternative outcomes.</div><div class="t9-mini"><b>2 · Registration Request</b>Guards, approval and composite eligibility.</div><div class="t9-mini"><b>3 · Patient Encounter</b>Richer branching, substates and clinical outcomes.</div></div>'},
5:{icon:'🪆',title:'From simple state to composite behavior',html:'<div class="t9-flow"><div class="t9-node"><strong>Serving Customer</strong>composite state</div><div class="t9-arrow">⊃</div><div class="t9-node">Authenticate</div><div class="t9-arrow">→</div><div class="t9-node">Select Transaction</div><div class="t9-arrow">→</div><div class="t9-node">Transaction</div></div>'},
6:{icon:'🔄',title:'Workflow mental model',html:'<div class="t9-flow"><div class="t9-node"><strong>Input</strong>request / object / information</div><div class="t9-arrow">→</div><div class="t9-node"><strong>Actions</strong>work is performed</div><div class="t9-arrow">→</div><div class="t9-node"><strong>Control flow</strong>decide / branch / synchronize</div><div class="t9-arrow">→</div><div class="t9-node"><strong>Outcome</strong>result of the workflow</div></div>'},
7:{icon:'◆',title:'Alternative routes: decide, then merge',html:'<div class="t9-flow"><div class="t9-node">Check request</div><div class="t9-arrow">→</div><div><div class="t9-diamond"><span>valid?</span></div></div><div class="t9-arrow">→</div><div class="t9-grid" style="flex:2"><div class="t9-mini"><b>[yes]</b>Process</div><div class="t9-mini"><b>[no]</b>Reject</div></div><div class="t9-arrow">→</div><div class="t9-node">Merge</div></div>'},
8:{icon:'⚡',title:'Parallel work is not a decision',html:'<div><div class="t9-fork"></div><div class="t9-grid"><div class="t9-mini"><b>Thread A</b>Prepare items</div><div class="t9-mini"><b>Thread B</b>Authorize payment</div><div class="t9-mini"><b>Object flow</b>Order / Invoice</div></div><div class="t9-fork"></div><p style="text-align:center;margin:8px 0 0;font-weight:800;color:var(--page-accent)">JOIN waits for required concurrent work</p></div>'},
9:{icon:'🏊',title:'Swimlanes expose responsibility and handoffs',html:'<div class="t9-lanes"><div class="t9-lane"><b>Student</b><div class="t9-action">Request registration</div></div><div class="t9-lane"><b>Registration System</b><div class="t9-action">Check capacity</div><div class="t9-action">Check prerequisites</div></div><div class="t9-lane"><b>Department</b><div class="t9-action">Review approval</div></div></div>'},
10:{icon:'📦',title:'Worked workflow: trace before you draw',html:'<div class="t9-flow"><div class="t9-node"><strong>Receive order</strong>identify the trigger</div><div class="t9-arrow">→</div><div class="t9-node"><strong>Process items</strong>identify actions</div><div class="t9-arrow">→</div><div class="t9-node"><strong>Apply guards</strong>identify alternatives</div><div class="t9-arrow">→</div><div class="t9-node"><strong>Synchronize</strong>identify parallel work</div><div class="t9-arrow">→</div><div class="t9-node"><strong>Dispatch</strong>identify the outcome</div></div>'},
11:{icon:'✏️',title:'Practice: model first, reveal later',html:'<div class="t9-grid"><div class="t9-mini"><b>University Registration</b>parallel validation + conditional approval</div><div class="t9-mini"><b>Food Delivery</b>parallel operations + cancellation</div><div class="t9-mini"><b>Hospital Treatment</b>multi-role workflow + clinical branching</div></div>'},
12:{icon:'🎯',title:'Choose the model from the question',html:'<div class="t9-compare"><div class="t9-model"><b>Sequence</b><p><strong>Question:</strong> Which participants exchange messages, and in what order?</p></div><div class="t9-model"><b>State</b><p><strong>Question:</strong> How does one object change and react across its lifetime?</p></div><div class="t9-model"><b>Activity</b><p><strong>Question:</strong> How does work branch, flow, synchronize and move across responsibilities?</p></div></div>'},
13:{icon:'✅',title:'Behavioral modeling mastery check',html:'<div class="t9-check"><div><b>Interaction</b><br>Read message order</div><div><b>Reactive behavior</b><br>Identify event/state/guard</div><div><b>Workflow</b><br>Distinguish decision from fork</div><div><b>Responsibility</b><br>Read swimlanes</div><div><b>Model selection</b><br>Justify Sequence vs State vs Activity</div></div>'}
};

(function(){
  document.body.dataset.topic='09';
  if(!document.querySelector('link[data-topic09-style]')){const l=document.createElement('link');l.rel='stylesheet';l.href='topic09.css';l.dataset.topic09Style='1';document.head.append(l)}
  const n=+document.body.dataset.page||1,s=document.getElementById('topic-sidebar'),m=document.getElementById('topic-mobile');
  const h='<div class="side-head"><small>Topic 09 · Chapters 13–14</small><strong>Behavioral Modeling with UML</strong></div>';
  const links=TOPIC09.map((p,i)=>`<a class="side-link ${i+1===n?'active':''}" href="${p[0]}"><span>${String(i+1).padStart(2,'0')}</span><span>${p[1]}</span></a>`).join('');
  if(s)s.innerHTML=h+links;if(m)m.innerHTML=TOPIC09.map((p,i)=>`<a class="${i+1===n?'active':''}" href="${p[0]}">${String(i+1).padStart(2,'0')} · ${p[1]}</a>`).join('');
  let a=document.getElementById('prev-link'),b=document.getElementById('next-link');if(a&&n>1){a.href=TOPIC09[n-2][0];a.hidden=false}if(b&&n<TOPIC09.length){b.href=TOPIC09[n][0];b.hidden=false}
  const hook=T9_HOOKS[n],article=document.querySelector('article.content');if(hook&&article&&!article.querySelector('.t9-hook')){const section=document.createElement('section');section.className='t9-hook';section.innerHTML=`<div class="t9-hook-head"><div class="t9-hook-icon" aria-hidden="true">${hook.icon}</div><div><small>Visual learning hook</small><h2>${hook.title}</h2></div></div>${hook.html}`;const target=article.querySelector('.objective')||article.querySelector('.hero');target?.insertAdjacentElement('afterend',section)}
})();
(()=>{if(!document.querySelector('script[data-cpcs-nav]')){const s=document.createElement('script');s.src='../../navigation-system.js';s.dataset.cpcsNav='1';document.head.append(s)}})();